wandb:
  entity: psuraj

experiment:
    project: "muse"
    name: "laiona6plus-f8-movq"
    output_dir: "fsx/suraj/laiona6plus-f8-movq"
    max_train_examples: 8974320 # toal sucessfully downloaded images for laiona6plus
    max_eval_examples: 8118
    save_every: 2000
    eval_every: 1000
    generate_every: 1000
    log_every: 50
    log_grad_norm_every: 500
    resume_from_checkpoint: latest
    resume_lr_scheduler: True

model:
    vq_model:
        type: "movq"
        pretrained: "openMUSE/movq-lion-high-res-f8-16384"
    
    text_encoder:
        type: "clip"
        pretrained: "openMUSE/clip-vit-large-patch14-penultimate"
    
    architecture: "uvit"

    transformer:
        vocab_size: 8256 # (8192 + 1 for <mask> = 8193 but 8256 is the next multiple of 8)
        hidden_size: 1024
        intermediate_size: 4096
        num_hidden_layers: 22
        num_attention_heads: 16
        in_channels: 256
        block_out_channels:
            - 512
            - 768
        block_has_attention:
            - True
            - True
        block_num_heads:
            - 8
            - 12
        num_res_blocks: 2
        patch_size: 1
        encoder_hidden_size: 768
        add_cross_attention: True
        project_encoder_hidden_states: False
        codebook_size: 16384
        num_vq_tokens: 1024
        initializer_range: 0.02
        norm_type: "rmsnorm"
        layer_norm_eps: 1e-6
        use_normformer: False
        use_encoder_layernorm: False
        use_bias: False
        hidden_dropout: 0.0
        attention_dropout: 0.0
        use_codebook_size_for_output: True
        layer_norm_before_mlm: True
        layer_norm_embedddings: True

    gradient_checkpointing: True
    enable_xformers_memory_efficient_attention: True


dataset:
    type: "text2image"
    params:
        train_shards_path_or_url: "pipe:aws s3 cp s3://muse-datasets/laion-aesthetic6plus-data/{00000..01210}.tar -"
        eval_shards_path_or_url: "pipe:aws s3 cp s3://muse-datasets/coco/2014/val/{00000..00010}.tar -"
        validation_prompts_file: "validation_prompts/dalle_mini_prompts.txt"
        batch_size: ${training.batch_size}
        shuffle_buffer_size: 1000
        num_workers: 4
        resolution: 256
        pin_memory: True
        persistent_workers: True
    preprocessing:
        max_seq_length: 77
        resolution: 256
        center_crop: False
        random_flip: False


optimizer:
    name: fused_adamw
    params: # default adamw params
        learning_rate: 1e-4
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8


lr_scheduler:
    scheduler: "constant_with_warmup"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 2000


training:
    gradient_accumulation_steps: 1
    batch_size: 96
    mixed_precision: "fp16"
    enable_tf32: True
    use_ema: False
    seed: 9345104
    max_train_steps: 677300
    overfit_one_batch: False
    cond_dropout_prob: 0.1
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: null
    guidance_scale: 7.0
    generation_timesteps: 16
    # related to vae code sampling
    use_soft_code_target: False
    use_stochastic_code: False
    soft_code_temp: 1.0
    eval_mask_ratios:
        - 1.0
        - 0.7
        - 0.5
        - 0.2
